# Generated by Django 6.0.3 on 2026-03-28 17:22

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='full_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='accounts',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
