# Generated by Django 6.0.3 on 2026-04-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_managers_accounts_city_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='country',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='area',
            field=models.CharField(default='Delmas 32', help_text='Ex: Delmas 32, Petion-Ville', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('USA', 'USA'), ('HT', 'Haiti')], max_length=10),
        ),
    ]
