# Generated by Django 6.0.3 on 2026-04-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_managers_remove_warehouse_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
