# Generated by Django 6.0.3 on 2026-04-07 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='staff_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='accounts.warehouse'),
        ),
    ]
