# Generated by Django 6.0.3 on 2026-04-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accounts_staff_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
