# Generated by Django 6.0.3 on 2026-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_warehouse_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='area',
            field=models.CharField(default='', help_text='Ex: Delmas 32, Petion-Ville', max_length=100),
        ),
    ]
