# Generated by Django 6.0.3 on 2026-04-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_warehouse_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('USA', 'USA'), ('HT', 'Haiti'), ('RD', 'Dominican Republic')], max_length=10),
        ),
    ]
