# Generated by Django 6.0.3 on 2026-04-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_warehouse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='label_code',
            field=models.CharField(default='', max_length=3),
        ),
    ]
