# Generated by Django 6.0.3 on 2026-05-18 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_warehouse_label_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('driver_license', 'Driver License'), ('national_id', 'National ID')], default='national_id', max_length=20)),
                ('front_image', models.ImageField(upload_to='kyc/front/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='kyc/back/')),
                ('selfie_image', models.ImageField(blank=True, null=True, upload_to='kyc/selfie/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
