# Generated by Django 6.0.3 on 2026-05-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_kyc_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('support_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('kyc_email', models.BooleanField(default=True)),
                ('shipment_email', models.BooleanField(default=True)),
            ],
        ),
    ]
