# Generated by Django 6.0.3 on 2026-05-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_dashboardsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='can_access_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='can_create_shipments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='can_delete_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='can_manage_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='can_view_customer_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='can_view_customer_phone',
            field=models.BooleanField(default=False),
        ),
    ]
