# Generated by Django 6.0.3 on 2026-06-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_accounts_can_access_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='can_manage_kyc',
            field=models.BooleanField(default=False),
        ),
    ]
