# Generated by Django 6.0.3 on 2026-06-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_accounts_can_manage_kyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='can_manage_kyc',
        ),
    ]
