# Generated by Django 6.0.3 on 2026-04-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='shipping_type',
            field=models.CharField(choices=[('air', 'Air'), ('sea', 'Sea')], max_length=10),
        ),
    ]
