# Generated by Django 6.0.3 on 2026-04-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_package_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
