# Generated by Django 6.0.3 on 2026-04-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_package_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
