# Generated by Django 6.0.3 on 2026-04-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_package_pickup_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_type', models.CharField(choices=[('air', 'Air'), ('sea', 'Sea')], max_length=10)),
                ('price_per_lb', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volumetric_divisor', models.IntegerField(default=139)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
