# Generated by Django 6.0.3 on 2026-04-13 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_warehouse_area'),
        ('shipping', '0005_pricingrule_alter_package_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_type', models.CharField(choices=[('air', 'Air'), ('sea', 'Sea')], max_length=10)),
                ('price_per_lb', models.DecimalField(decimal_places=2, max_digits=6)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='accounts.warehouse')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='accounts.warehouse')),
            ],
        ),
    ]
