# Generated by Django 6.0.3 on 2026-04-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_routepricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(default='Shipping'),
        ),
    ]
