# Generated by Django 6.0.3 on 2026-04-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_alter_package_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
