# Generated by Django 6.0.3 on 2026-04-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_category_surcharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routepricing',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='routepricing',
            name='origin',
        ),
        migrations.AddField(
            model_name='routepricing',
            name='destination_type',
            field=models.CharField(choices=[('USA', 'USA'), ('HT', 'Haiti'), ('RD', 'Dominican Republic')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routepricing',
            name='origin_type',
            field=models.CharField(choices=[('USA', 'USA'), ('HT', 'Haiti'), ('RD', 'Dominican Republic')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
