# Generated by Django 6.0.3 on 2026-04-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0010_contact_created_at_contact_is_guest_contact_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='pickup_code',
        ),
        migrations.AddField(
            model_name='package',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
