# Generated by Django 6.0.3 on 2026-04-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0011_remove_package_pickup_code_package_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
