# Generated by Django 6.0.3 on 2026-05-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0012_alter_package_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('in_transit', 'In_Transit'), ('ready_pickup', 'Ready_Pickup'), ('delivered', 'Delivered'), ('canceled', 'canceled')], default='received', max_length=20),
        ),
    ]
