# Generated by Django 6.0.3 on 2026-05-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0013_package_pickup_code_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='package',
            name='shipment_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], default='standard', max_length=10),
        ),
        migrations.AlterField(
            model_name='routepricing',
            name='shipping_type',
            field=models.CharField(choices=[('air', 'Air Freight'), ('sea', 'Sea Freight')], max_length=10),
        ),
    ]
