# Generated by Django 6.0.3 on 2026-05-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0014_package_payment_status_package_shipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
    ]
